version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: sc_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: sc_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/smartcanteen
      - JWT_SECRET=supersecretchange
    depends_on:
      - mongo
    command: ["npm","run","dev"]

volumes:
  mongo_data:
